stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  APP: "my-app"

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
    - echo "wtoKSO8blMv32XFOzYxal304rIZrjdbJ" | docker login -u ""robot$demo_docker_ci3+demo_docker_ci"" "$HARBOR_HOST" --password-stdin
  script:
    - docker build -t my-docker-image .
    - docker tag my-docker-image $HARBOR_HOST/$HARBOR_PROJECT/$APP:$CI_JOB_ID
    - docker tag my-docker-image $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$APP:$CI_JOB_ID
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
