build_image:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
      pull_policy: if-not-present        # <<< вот это
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache git
    - git --version
  script:
    - docker build \
        -f "$CI_PROJECT_DIR/Dockerfile" \
        -t "$HARBOR_HOST/$HARBOR_PROJECT/$APP:$CI_COMMIT_SHORT_SHA" \
        "$CI_PROJECT_DIR" > build.log 2>&1
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" "$HARBOR_HOST"
    - docker push "$HARBOR_HOST/$HARBOR_PROJECT/$APP:$CI_COMMIT_SHORT_SHA"
    - docker tag  "$HARBOR_HOST/$HARBOR_PROJECT/$APP:$CI_COMMIT_SHORT_SHA" \
                  "$HARBOR_HOST/$HARBOR_PROJECT/$APP:latest"
    - docker push "$HARBOR_HOST/$HARBOR_PROJECT/$APP:latest"
  tags:
    - docker
  artifacts:
    when: always
    paths:
      - build.log